# Generated by Django 3.0.8 on 2020-08-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('video', models.FileField(upload_to='uploads/videos/')),
            ],
        ),
    ]
