# Generated by Django 3.0.8 on 2020-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='No Thumbnail', upload_to='uploads/thumbnails/'),
            preserve_default=False,
        ),
    ]
