# Generated by Django 3.0.8 on 2020-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.CharField(default='Unknown Uploader', max_length=256),
            preserve_default=False,
        ),
    ]
