# Generated by Django 3.0.8 on 2020-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200804_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.CharField(max_length=256),
        ),
    ]
