# Generated by Django 3.0.8 on 2020-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20200805_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploader_username',
            field=models.CharField(default='Unknown Uploader', max_length=256),
            preserve_default=False,
        ),
    ]
