# Generated by Django 3.0.8 on 2020-08-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_uploader_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploader_username',
        ),
    ]
