# Generated by Django 3.0.8 on 2020-08-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20200805_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.CharField(max_length=256),
        ),
    ]
