# Generated by Django 3.0.8 on 2020-08-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20200806_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('videotitle', models.CharField(max_length=256)),
                ('likestatus', models.BooleanField(default=False)),
            ],
        ),
    ]
