# Generated by Django 3.0.8 on 2020-08-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20200806_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likestatus',
            new_name='is_liked',
        ),
    ]
