# Generated by Django 3.0.8 on 2020-08-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20200807_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
