# Generated by Django 3.0.8 on 2020-08-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_remove_like_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
